sudo: required
after_success:
- coveralls
env:
- TOXENV=check-isort
- TOXENV=check-flake8
- TOXENV=py36
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=py26
- TOXENV=pypy
install:
- pip install -U tox
- pip install coveralls
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
before_script:
- pip install -e .
- mkdir -p ~/.pet
- pet recreate
script:
- tox
