#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
printf "\n\e[1;36mGive name of shell you are using\nAccepting bash/ zsh\e[0m\n"
read shell
if [ $(echo "$shell" | grep "bash") ]; then

    if [ $(uname -s) = "Darwin" ]; then
        if [ -d "$(brew --prefix)/etc/bash_completion.d/" ]; then
            bash_completions="$(brew --prefix)/etc/bash_completion.d"
        fi
    fi

    if [ -z "$bash_completions" ]; then
        if [ -d '/etc/bash_completion.d' ]; then
                bash_completions='/etc/bash_completion.d'
            else
                bash_completions="$HOME/.bash_completion"
        fi
    fi

    if [ "$bash_completions" == "$HOME/.bash_completion" ]; then
            echo ". $DIR/complete.bash" >> "$bash_completions"
        else
            echo ". $DIR/complete.bash" > "$bash_completions/pet"
    fi

elif [ $(echo "$shell" | grep "zsh") ]; then
    if [ -z "$ZDOTDIR" ]; then
        rc_path="$HOME/.zshrc"
    else
        rc_path="$ZDOTDIR/.zshrc"
    fi
    printf "autoload -U +X compinit && compinit\n" >> "$rc_path"
    printf "autoload -U +X bashcompinit && bashcompinit\n" >> "$rc_path"
    printf "source \"$DIR/complete.bash\"\n" >> "$rc_path"
    printf "\n\n\e[1;32mAuto-completion should work in \e[1;31mnew\e[1;32m zsh terminals\n\e[0m\n"
else
    echo "Shell $shell is not supported"
fi
